name: publish to pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
      
      - name: No Jekyll
        run: touch build/.nojekyll
      
      - name: Upload
        uses: actions/upload-pages-artifact
        path: build

